export const types = {
  UPDATE_RESULTS: "UPDATE_RESULTS",
  SET_LOADING_STATUS: "SET_LOADING_STATUS",
  SET_ERRORS: "SET_ERRORS",
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  SET_MODAL_STATUS: "SET_MODAL_STATUS",
};
