"use strict";
exports.__esModule = true;
exports.types = void 0;
exports.types = {
    UPDATE_RESULTS: "UPDATE_RESULTS",
    SET_LOADING_STATUS: "SET_LOADING_STATUS",
    SET_LOADING_BOOKS_STATUS: "SET_LOADING_BOOKS_STATUS",
    SET_ERRORS: "SET_ERRORS",
    SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
    SET_MODAL_STATUS: "SET_MODAL_STATUS",
    SET_LAST_API_ADDRESS: "SET_LAST_API_ADDRESS"
};
