version: "3.8"

services:
  postgres:
    image: postgres:14.4
    restart: always
    container_name: book-searcher-db
    environment:
      POSTGRES_DB: book-searcher
      POSTGRES_USER: librarian
      POSTGRES_PASSWORD: librarian
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
