"use strict";
exports.__esModule = true;
var dotenv_1 = require("dotenv");
dotenv_1["default"].config({ path: ".env" });
var express_1 = require("express");
var body_parser_1 = require("body-parser");
var errors_1 = require("./middlewares/errors");
var express_session_1 = require("express-session");
var session_1 = require("./config/session");
var booksRoute_1 = require("./packages/books/booksRoute");
var usersRoute_1 = require("./packages/users/usersRoute");
var app = express_1["default"]();
app.use(body_parser_1["default"].json());
app.use(body_parser_1["default"].urlencoded({ extended: false }));
app.use(express_session_1["default"](session_1.sessionConfig));
app.use("/api/books", booksRoute_1.booksRoute);
app.use("/api/users", usersRoute_1.usersRoute);
app.use(errors_1.notFound);
app.use(errors_1.catchErrors);
var port = process.env.PORT || 3080;
app.listen(port, function () {
    console.log("Server is up");
});
